# Use postgres/example user/password credentials
version: '3.1'

services:
  onethemat_dev:
    image: postgres:14
    container_name: onthemat_psql_dev
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Seoul
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - /var/db/docker/postgres/onthemat/dev/data:/data/db
    expose: 
      - '${POSTGRES_PORT}'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    command: -p ${POSTGRES_PORT}