# Use postgres/example user/password credentials
version: '3.1'

services:
  onthemat_test_db:
    image: postgres:latest
    container_name: psql_repo_test
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose: 
      - '${POSTGRES_PORT}'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    command: -p ${POSTGRES_PORT}