// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AcademyService is an autogenerated mock type for the AcademyService type
type AcademyService struct {
	mock.Mock
}

// VerifyBusinessMan provides a mock function with given fields: businessCode
func (_m *AcademyService) VerifyBusinessMan(businessCode string) error {
	ret := _m.Called(businessCode)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(businessCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAcademyService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAcademyService creates a new instance of AcademyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAcademyService(t mockConstructorTestingTNewAcademyService) *AcademyService {
	mock := &AcademyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
