// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AreaUsecase is an autogenerated mock type for the AreaUsecase type
type AreaUsecase struct {
	mock.Mock
}

// CreateSiDo provides a mock function with given fields: ctx, fileUrl
func (_m *AreaUsecase) CreateSiDo(ctx context.Context, fileUrl string) error {
	ret := _m.Called(ctx, fileUrl)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, fileUrl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAreaUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewAreaUsecase creates a new instance of AreaUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAreaUsecase(t mockConstructorTestingTNewAreaUsecase) *AreaUsecase {
	mock := &AreaUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
