// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	ent "onthemat/pkg/ent"

	mock "github.com/stretchr/testify/mock"
)

// ImageRepository is an autogenerated mock type for the ImageRepository type
type ImageRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, image, userID
func (_m *ImageRepository) Create(ctx context.Context, image *ent.Image, userID int) error {
	ret := _m.Called(ctx, image, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Image, int) error); ok {
		r0 = rf(ctx, image, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewImageRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewImageRepository creates a new instance of ImageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewImageRepository(t mockConstructorTestingTNewImageRepository) *ImageRepository {
	mock := &ImageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
