// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	jwt "github.com/golang-jwt/jwt/v4"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TokenService is an autogenerated mock type for the TokenService type
type TokenService struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: uuid, userId, loginType, userType, expired
func (_m *TokenService) GenerateToken(uuid string, userId int, loginType string, userType string, expired int) (string, error) {
	ret := _m.Called(uuid, userId, loginType, userType, expired)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, int, string, string, int) string); ok {
		r0 = rf(uuid, userId, loginType, userType, expired)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int, string, string, int) error); ok {
		r1 = rf(uuid, userId, loginType, userType, expired)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExpiredAt provides a mock function with given fields: expired
func (_m *TokenService) GetExpiredAt(expired int) time.Time {
	ret := _m.Called(expired)

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(int) time.Time); ok {
		r0 = rf(expired)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// ParseToken provides a mock function with given fields: tokenString, result
func (_m *TokenService) ParseToken(tokenString string, result jwt.Claims) error {
	ret := _m.Called(tokenString, result)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, jwt.Claims) error); ok {
		r0 = rf(tokenString, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTokenService interface {
	mock.TestingT
	Cleanup(func())
}

// NewTokenService creates a new instance of TokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTokenService(t mockConstructorTestingTNewTokenService) *TokenService {
	mock := &TokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
