// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UserYogaUsecase is an autogenerated mock type for the UserYogaUsecase type
type UserYogaUsecase struct {
	mock.Mock
}

type mockConstructorTestingTNewUserYogaUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserYogaUsecase creates a new instance of UserYogaUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserYogaUsecase(t mockConstructorTestingTNewUserYogaUsecase) *UserYogaUsecase {
	mock := &UserYogaUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
