info:
  contact: {}
  termsOfService: http://swagger.io/terms/
  title: Go Boilerplate
  version: 1.0.4
paths:
  /api/v1/auth/kakao:
    get:
      consumes:
      - application/json
      description: 카카오 리디렉션 URL을 가져오는 API
      produces:
      - application/json
      responses:
        "302":
          description: Found
        "500":
          description: Internal Server Error
      summary: 카카오 로그인 URL
      tags:
      - Auth
securityDefinitions:
  JwtToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
